### PR TITLE
arguments support added

### LINKED ISSUE #54: some flag support are not there.
As I can see lib does not support these two arguments' flags. 
1. x-overflow: 'reject-publish',  
2. 'x-queue-mode': 'lazy'

I have tried to update these flags here is my code but getting exception. 

`const { BaseQueueHandler, Rabbit } = require('rabbit-queue');
const rabbit = new Rabbit(process.env.RABBIT_URL || 'amqp://localhost', {
  prefetch: 1, //default prefetch from queue
  replyPattern: true, //if reply pattern is enabled an exclusive queue is created
  scheduledPublish: false,
  prefix: '', //prefix all queues with an application name
  socketOptions: {} // socketOptions will be passed as a second param to amqp.connect and from ther to the socket library (net or tls)
});

rabbit.on('connected', () => {
  //create queues, add halders etc.
  //this will be called on every reconnection too
  console.log("Rabbit-queue Rabbit-queue !!!");
});

rabbit.on('disconnected', (err = new Error('Rabbitmq Disconnected')) => {
  //handle disconnections and try to reconnect
  console.error(err);
  setTimeout(() => rabbit.reconnect(), 100);
});

class BatchBaseWorker extends BaseQueueHandler {
  constructor(queueName) {
    super(queueName, rabbit, {
      prefetch: 25,
      retries: 0,
      retryDelay: 1000,
      logEnabled: true,
      scope: 'SINGLETON',
      createAndSubscribeToQueue: true,
    });
    this.queueName = queueName;
  }

  async createQueues() {
    this.queue = await this.rabbit
      .createQueue(this.queueName, { ...this.getQueueOptions(), prefetch: this.prefetch,   maxLength: 25 }, (msg, ack) => {
        this.tryHandle(0, msg, ack).catch((e) => this.logger.error(e));
      })
      .catch((error) => this.logger.error(error));
      let queueOptions = { 
        arguments: {
        'x-overflow': 'reject-publish',
        'x-queue-mode': 'lazy'
      }}
     let res = await this.queue.channel.assertQueue(this.queueName, queueOptions);
     console.log(this.queue.options);
     console.log(res);
    this.dlq = await this.rabbit
      .createQueue(this.dlqName, this.getDlqOptions())
      .catch((error) => this.logger.error(error));
  }
}
new BatchBaseWorker('sauron_content');`

Exception message :   Channel closed by server: 406 (PRECONDITION-FAILED) with message "PRECONDITION_FAILED - inequivalent arg 'x-max-length' for queue 'sauron_content' in vhost '/': received '[{<<"type">>,longstr,<<"byte">>},{<<"value">>,byte,25}]' but current is '25'" 

package version : 5.4.1 

https://github.com/Workable/rabbit-queue/blob/master/ts/queue.ts#L54

### PR DESCRIPTION
**Pull request by kundan8239**
Resolves #54

### CODE REVIEW

File: ts/queue.ts [hunk 1]
```diff
@@ -38,7 +38,7 @@ export default class Queue {
       expires,
       deadLetterExchange,
       deadLetterRoutingKey,
-      maxLength
+      maxLength,
```
Comment (nikostoulas) [inline ts/queue.ts:41]: Nit: You could destructure arguments here

**Review by nikostoulas — APPROVED** [review]
Thanks for your pr @kundan8239 !

File: ts/queue.ts (hunk 1 above)
Comment (kundan8239) [reply ts/queue.ts:41]: Hello @nikostoulas 
made a change, plz have a look.

Comment (nikostoulas) [inline ts/queue.ts:41]:
```suggestion
      maxLength,
      arguments
```

File: ts/queue.ts [hunk 2]
```diff
@@ -48,12 +48,12 @@ export default class Queue {
...
+      arguments: { ...this.options.arguments }
```
Comment (nikostoulas) [inline ts/queue.ts:52]:
```suggestion
      arguments
```

If you destruture arguments in L42 you use it like this here

File: test/queue.test.ts [hunk 3]
```diff
@@ -46,7 +46,8 @@ describe('Test Queue class', function () {
         expires: undefined,
         deadLetterExchange: undefined,
         deadLetterRoutingKey: undefined,
-        maxLength: undefined
+        maxLength: undefined,
+        arguments: {}
```
Comment (nikostoulas) [inline test/queue.test.ts:50]: ❓ Were you having issues with arguments being undefined?

File: ts/queue.ts (hunk 1 above)
Comment (kundan8239) [reply ts/queue.ts:41]: if I'm not wrong a strict mode does allow us to create a variable name with arguments as it is predefined in javascript. it gives me an error that's why I have not destructed on L42.

File: test/queue.test.ts (hunk 3 above)
Comment (kundan8239) [reply test/queue.test.ts:50]: because of destructed  arguments  like that
`arguments: {...this.option.arguments}`  in case of the undefined test cases are breaking.

File: ts/queue.ts (hunk 1 above)
Comment (nikostoulas) [reply ts/queue.ts:41]: Oh yes, makes sense

**Review by nikostoulas — APPROVED** [review]
